"""initial schema

Revision ID: 663262daa51e
Revises: 
Create Date: 2025-11-24 22:26:01.154265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '663262daa51e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'caller_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('calls', 'receiver_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('calls', 'call_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calls', 'call_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('calls', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.alter_column('intents', 'intent_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.alter_column('intents', 'intent_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.alter_column('calls', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('calls', 'call_end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calls', 'call_start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('calls', 'receiver_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('calls', 'caller_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
